# -*- coding: utf-8 -*-
"""DocumentTitling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ThuGyJwS7QbrYGqVXDsTvCOqFGK6RpH9
"""

#Chris Kinley
#11/16

from nltk.stem.snowball import SnowballStemmer
import re

regex = re.compile('[^a-zA-Z0-9]')


# Finds month names in the a tokenized document and finds the year associated with it. Returns a dictionary of each month/year combo that appears and which spots in the list it appears in
def find_dates(list):
  return_dict = {}
  months = ["january", "february", "march", "april", "may", "june", "july", "august", "september", "october", "november", "december"]
  for i in range(len(list)):
    for month in months:
      if month in list[i].lower():
        for j in range(max(i-4,0),i+5):
          try:
            year = int(list[j])
          except:
            continue
          if year>1900 and year<2100:
            date = month + " " + str(year)
            if date not in return_dict:
              return_dict[date] = [i]
            else:
              return_dict[date].append(i)
  return return_dict



# Stemming to find roots
stemmer = SnowballStemmer("english")


#Section to specifically load up the one file
path = "/content/Sprague Project Funding Agreement.txt"
#"/content/Sprague First Renewal License & Operating Agree Merrill Warehouse.txt"


#stopwords list
stopwords = ['', "i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you", "your", "yours", "yourself", "yourselves", "he", "him", "his", "himself", "she", "her", "hers", "herself", "it", "its", "itself", "they", "them", "their", "theirs", "themselves", "what", "which", "who", "whom", "this", "that", "these", "those", "am", "is", "are", "was", "were", "be", "been", "being", "have", "has", "had", "having", "do", "does", "did", "doing", "a", "an", "the", "and", "but", "if", "or", "because", "as", "until", "while", "of", "at", "by", "for", "with", "about", "against", "between", "into", "through", "during", "before", "after", "above", "below", "to", "from", "up", "down", "in", "out", "on", "off", "over", "under", "again", "further", "then", "once", "here", "there", "when", "where", "why", "how", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just", "don", "should", "now", "shall", "page", "---"]

# load up files as needed (currently doing just 1)
with open(path, "r") as file:
  text=file.read().split()


# create 1 word frequency dictionary
freq_dict ={}
for words in text:
  word = stemmer.stem(regex.sub('',words.lower()))
  if word not in stopwords:
    if word in freq_dict:
      freq_dict[word]= freq_dict[word]+1
    else:
      freq_dict[word] = 1




#creating two word frequency dictionary
bifreq_dict = {}
old_word=""
two_word=""
for words in text:
  word = regex.sub("",words.lower())
  if word not in stopwords:
    two_word = old_word + " " + word
    if two_word in bifreq_dict:
      bifreq_dict[two_word]= bifreq_dict[two_word]+1
    else:
      bifreq_dict[two_word] = 1
    old_word = word

# 3 word frequency dictionary (might have issues, doesn't seem to find any 3 word combinations that repeat for this specific document)
trifreq_dict = {}
first_word=""
second_word =""
three_word=""
for words in text:
  word = regex.sub("",words.lower())
  if word not in stopwords:
    three_word = first_word + " " + second_word + " " + word
    if two_word in trifreq_dict:
      trifreq_dict[three_word]= trifreq_dict[three_word]+1
    else:
      trifreq_dict[three_word] = 1
    first_word = second_word
    second_word = word
# sorts all the frequency dictionaries by frequencies
freq_dict = {k: v for k, v in sorted(freq_dict.items(), key=lambda item: item[1], reverse=True)}
bifreq_dict = {k: v for k, v in sorted(bifreq_dict.items(), key=lambda item: item[1], reverse=True)}
trifreq_dict = {k: v for k, v in sorted(trifreq_dict.items(), key=lambda item: item[1], reverse=True)}

# printing
print(find_dates(text))
print(text)
print(freq_dict)
print(bifreq_dict)
print(trifreq_dict)

# Section to analyze above results to come up with title TO BE DONE